# Generated by Django 5.2.4 on 2025-11-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_progressphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressentry',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='main.memberprofile'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('body_fat_pct', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='main.memberprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
